/**
 * License compliance — generates CREDITS.md and src/credits.json
 * Fails with exit code 1 if any asset lacks a resolvable license.
 */
import fs from 'node:fs';
import path from 'node:path';
import type { FetchResult } from './fetchers/types.js';

export interface CreditEntry {
  id: string;
  title: string;
  author: string;
  sourceUrl: string;
  license: string;
  licenseUrl: string;
  downloadDate: string;
}

export function validateLicenses(results: Map<string, FetchResult>): void {
  const missing: string[] = [];

  for (const [id, result] of results) {
    if (!result.license || result.license === 'UNKNOWN') {
      missing.push(id);
    }
    if (!result.licenseUrl) {
      missing.push(`${id} (no license URL)`);
    }
  }

  if (missing.length > 0) {
    console.error('\n[credits] FATAL: Assets with missing/unresolvable licenses:');
    for (const m of missing) {
      console.error(`  - ${m}`);
    }
    process.exit(1);
  }
}

export function generateCredits(results: Map<string, FetchResult>, outputDir: string): void {
  const entries: CreditEntry[] = [];

  for (const [id, result] of results) {
    entries.push({
      id,
      title: result.attribution.title,
      author: result.attribution.author,
      sourceUrl: result.attribution.sourceUrl,
      license: result.license,
      licenseUrl: result.licenseUrl,
      downloadDate: result.attribution.downloadDate,
    });
  }

  // Sort by category/id for stable output
  entries.sort((a, b) => a.id.localeCompare(b.id));

  // Write CREDITS.md
  const md = buildCreditsMarkdown(entries);
  fs.writeFileSync(path.join(outputDir, 'CREDITS.md'), md, 'utf-8');
  console.log(`[credits] Generated CREDITS.md (${entries.length} assets)`);

  // Write src/credits.json for in-app attribution panel
  const jsonDir = path.join(outputDir, 'src');
  fs.mkdirSync(jsonDir, { recursive: true });
  fs.writeFileSync(
    path.join(jsonDir, 'credits.json'),
    JSON.stringify({ assets: entries, generatedAt: new Date().toISOString() }, null, 2),
    'utf-8'
  );
  console.log(`[credits] Generated src/credits.json`);
}

function buildCreditsMarkdown(entries: CreditEntry[]): string {
  const lines: string[] = [
    '# 3D Asset Credits',
    '',
    'This file is auto-generated by `npm run assets:refresh`. Do not edit manually.',
    '',
    `Generated: ${new Date().toISOString().split('T')[0]}`,
    '',
    '| Asset | Author | License | Source |',
    '|-------|--------|---------|--------|',
  ];

  for (const e of entries) {
    const licenseLink = `[${e.license}](${e.licenseUrl})`;
    const sourceLink = `[Link](${e.sourceUrl})`;
    lines.push(`| ${e.title} | ${e.author} | ${licenseLink} | ${sourceLink} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## License Details');
  lines.push('');

  // Group by license type
  const byLicense = new Map<string, CreditEntry[]>();
  for (const e of entries) {
    const group = byLicense.get(e.license) || [];
    group.push(e);
    byLicense.set(e.license, group);
  }

  for (const [license, group] of byLicense) {
    lines.push(`### ${license}`);
    lines.push('');
    for (const e of group) {
      lines.push(`- **${e.title}** by ${e.author} — [source](${e.sourceUrl}) (downloaded ${e.downloadDate})`);
    }
    lines.push('');
  }

  return lines.join('\n');
}
